"""The configurations the MTDSim lineage evaluated on --- `tab:lineage-configurations`.

Chapter 2 (§2.2) float, emitted from `data/misc/lineage_configurations.yaml` so
no value is typed here (`figure_table_conventions.md` §h) and every cell's
locator sits in the emitted file's comment header, where it can be checked.

Why it exists: supervisor ruling E5 (register, 2026-09-22) --- every number in
the experimental setup needs a source, and a value a prior study ran is the
cheapest. Table 5.1 cites these studies against its own values; this table is
where a reader sees the range the lineage has run.

Rows are parameters, in Table 5.1's order and words, so the two tables read
side by side; columns are the studies. A dash is a value the study does not
state (decoded in the caption, §b4).

Usage:  python tools/ch2_lineage_configurations_table.py
"""

from __future__ import annotations

from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "data" / "misc" / "lineage_configurations.yaml"
OUT = REPO / "docs" / "thesis" / "tables" / "tab_2-2b_lineage_configurations.tex"

# Column widths in cm. With @{} at both edges the tabular is the widths plus
# 12 pt per interior boundary (§k rule 5): 14.7 cm + 3 x 12 pt = 15.97 cm
# against the 16.0 cm text width.
PARAM_WIDTH = 3.0
STUDY_WIDTH = {"brown2023": 3.7, "zhang2023": 4.6, "ho2024": 3.4}

CAPTION_SHORT = "The configurations of the MTDSim lineage"
CAPTION_LONG = (
    "The configurations the studies of the MTDSim lineage evaluated on. "
    "Values separated by semicolons were each run; a dash marks a value the "
    "study does not state. Ho gives the interval and the run's end without a "
    "unit; the simulator Ho ran counts in seconds \\citep{zhang2023}. "
    "Tay \\citep{tay2024} states no network, timing or run value."
)


def main() -> None:
    spec = yaml.safe_load(SOURCE.read_text())
    studies = spec["studies"]
    rows = spec["rows"]

    cols = "@{}P{%.1fcm}" % PARAM_WIDTH + "".join(
        "P{%.1fcm}" % STUDY_WIDTH[s["key"]] for s in studies
    ) + "@{}"
    header = " & ".join(
        ["Parameter"] + [f"{s['name']} \\citep{{{s['key']}}}" for s in studies]
    )

    lines = [
        "% GENERATED by tools/ch2_lineage_configurations_table.py from",
        "% data/misc/lineage_configurations.yaml --- edit the YAML, not this file.",
        "% Locators, one per cell (the caption's claims are checkable against these):",
    ]
    for row in rows:
        for s in studies:
            cell = row[s["key"]]
            shown = cell["value"] if cell["value"] is not None else "---"
            lines.append(f"%   {row['parameter']} / {s['name']}: {shown}  [{cell['locator']}]")
    lines += [
        "\\begin{table}[htbp]",
        "  \\centering",
        f"  \\caption[{CAPTION_SHORT}]{{{CAPTION_LONG}}}",
        "  \\label{tab:lineage-configurations}",
        "  \\tablestyle",
        f"  \\begin{{tabular}}{{{cols}}}",
        "    \\toprule",
        f"    {header} \\\\",
        "    \\midrule",
    ]
    for row in rows:
        cells = [row["parameter"]] + [
            row[s["key"]]["value"] if row[s["key"]]["value"] is not None else "---"
            for s in studies
        ]
        lines.append("    " + " & ".join(cells) + " \\\\")
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
