#!/usr/bin/env python3
"""Appendix table: time lost per MTD deployment under other windows and bin
widths (Marc 2026-09-25 on the §4.5 draft: "every time you see a number ...
is this defensible, is this strictly conventional?").

The 750 s before / 1 250 s after window and the 125 s bins are declared
analysis choices with no source to borrow from (no prior paper measures an
attacker's pace around a deployment). The 1 250 s after is derived: at the
2 000 s interval the next deployment's before-window starts there. The 750 s
split and the bin width are the choices this table moves. Every value is
recomputed from the corpus through disruption.py's own estimator; nothing is
hard-coded.

Usage: python tools/ch5_timelost_window_table.py
"""
from __future__ import annotations

import sys

import numpy as np

from _ch5_style import LONG, TAB_DIR, REPO

sys.path.insert(0, str(REPO / "data" / "results" / "ch5_defended"))
import disruption as D  # noqa: E402

AFTER = 1250
BEFORES = (500, 750, 1000)
WIDTHS = (62.5, 125.0, 250.0)
DECLARED = (750, 125.0)
ARMS = (("movement", "APT attacker model"), ("baseline", "Baseline attacker"))
STEM = "tab_C-5_timelost_window"


def time_lost(before: int, width: float) -> dict:
    D.EDGES = np.arange(-before, AFTER + width / 2, width)
    D.PRE = D.EDGES[:-1] < 0
    runs = D.load({2000})
    none = {(r["arm"], r["profile"], r["seed"]): r for r in runs if r["cond"] == "none"}
    out = {}
    for arm, _ in ARMS:
        for m in D.MECHANISMS:
            rs = [r for r in runs if r["arm"] == arm and r["cond"] == m and r["interval"] == 2000]
            num, den = D._stack(rs, None)
            pn, pd = D._stack(rs, none)
            out[(arm, m)] = D._time_lost(num.sum(0), den.sum(0)) - D._time_lost(pn.sum(0), pd.sum(0))
    return out


def main() -> None:
    grid = {(b, w): time_lost(b, w) for b in BEFORES for w in WIDTHS}
    # the bin width's largest effect on any cell, at every split
    width_gap = max(abs(grid[(b, w)][k] - grid[(b, DECLARED[1])][k])
                    for b in BEFORES for w in WIDTHS for k in grid[(b, w)])
    cols = [(b, DECLARED[1]) for b in BEFORES]
    lines = [
        "% GENERATED by tools/ch5_timelost_window_table.py --- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \caption[Time lost per MTD deployment under other windows]{Time lost per MTD deployment, in seconds, at the "
        r"2\,000\,s deployment interval, with the window before each deployment set to 500, 750 (as declared) or "
        r"1\,000\,s; the window after is 1\,250\,s throughout. Bins of 62.5 or 250\,s in place of 125\,s change no "
        r"value by more than %d\,s.}" % int(np.ceil(width_gap)),
        r"  \label{tab:timelost-window}",
        r"  \tablestyle",
        r"  \begin{tabular}{@{}l" + "r" * (2 * len(cols)) + "@{}}",
        r"    \toprule",
        "    & " + " & ".join(r"\multicolumn{%d}{c}{%s}" % (len(cols), name) for _, name in ARMS) + r" \\",
        "    " + " ".join(r"\cmidrule(lr){%d-%d}" % (2 + i * len(cols), 1 + (i + 1) * len(cols))
                         for i in range(len(ARMS))),
        "    Before (s) & " + " & ".join(r"%s" % (r"1\,000" if b == 1000 else str(b)) for _ in ARMS for b, _ in cols) + r" \\",
        r"    \midrule",
    ]
    order = sorted(D.MECHANISMS, key=lambda m: -grid[DECLARED][("movement", m)])
    for m in order:
        cells = []
        for arm, _ in ARMS:
            for c in cols:
                v = grid[c][(arm, m)]
                s = "%d" % round(v)
                cells.append(("$-$" + s[1:]) if s.startswith("-") else s)
        lines.append("    %s & %s \\\\" % (LONG[m], " & ".join(cells)))
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    path = TAB_DIR / f"{STEM}.tex"
    path.write_text("\n".join(lines))
    print(f"wrote {path.relative_to(REPO)} (bin width moves no value by more than {width_gap:.1f} s)")


if __name__ == "__main__":
    main()
