#!/usr/bin/env python3
"""Appendix table: attack confidentiality under other detectors (app:detector-memory).

Section 4.5's detector flags an action when the attacker has taken at least
theta actions in the 60 s up to and including it, theta set at the baseline
attacker's median count (ruling C, 2026-09-29, handoff
2026-09-29_s45_equation_clarity.md). This table moves both choices.

  WINDOW: 60, 90, 300 and 600 s --- the production defaults that bracket the
  declared one (record 14: Snort 3 port-scan low 60 s, medium 90 s, high 600 s;
  Zeek's scan policy 5 min). The alarm rule is held: theta is re-set at the
  baseline attacker's median count under each window.
  COUNT, at the 60 s window: theta from 2 to 6 actions.

Each row gives the share of the baseline attacker's actions the alarm flags,
and attack confidentiality over the whole run for each attacker (every action
of every run pooled), from the same no-defence corpus as Figure 5.2(b).
Nothing is typed.

    PYTHONPATH=src python tools/ch5_detector_sweep_table.py
"""
from __future__ import annotations

import sys

import numpy as np

from _ch5_style import TAB_DIR, REPO

sys.path.insert(0, str(REPO / "data" / "results" / "ch5_s531_unopposed"))
sys.path.insert(0, str(REPO / "src"))
import analyse as A  # noqa: E402

STEM = "tab_C-4_detector_sweep"
WINDOWS = (60.0, 90.0, 300.0, 600.0)
COUNTS = (2, 3, 4, 5, 6)
DECLARED = (60.0, 3)
SERIES = (*A.PROFILES[:4], "baseline")
LABEL = {A.PROFILES[0]: "$c_1$", A.PROFILES[1]: "$c_2$", A.PROFILES[2]: "$c_3$", A.PROFILES[3]: "$c_4$",
         "baseline": "baseline"}


def pct(v: float) -> str:
    return "%d" % round(100 * v)


def main() -> None:
    movement, baseline, _ = A.load()
    acts = {p: [A._actions_movement(r)[0] for r in movement[("targeted", A.CORE, p)]] for p in A.PROFILES[:4]}
    acts["baseline"] = [A._actions_baseline(row)[0] for row in baseline[A.CORE]]

    def levels(p, w):
        return np.asarray([d for a in acts[p] for _, d in A._detector_levels(a, w)])

    rows = []  # (window, theta, rule-set?, baseline flagged, {p: confidentiality})
    for w in WINDOWS:
        lv = {p: levels(p, w) for p in SERIES}
        th = float(np.median(lv["baseline"]))
        rows.append((w, th, True, float((lv["baseline"] >= th).mean()), {p: float((lv[p] < th).mean()) for p in SERIES}))
    lv = {p: levels(p, 60.0) for p in SERIES}
    for th in COUNTS:
        if th == DECLARED[1]:
            continue
        rows.append((60.0, float(th), False, float((lv["baseline"] >= th).mean()), {p: float((lv[p] < th).mean()) for p in SERIES}))

    def order_holds(conf):
        c = [conf[p] for p in SERIES]
        return all(x > c[-1] for x in c[:-1])

    L = [
        "% GENERATED by tools/ch5_detector_sweep_table.py --- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \caption[Attack confidentiality under other detectors]{Attack confidentiality over the whole run with no "
        r"defence running, in per cent, under detectors with other windows and alarm counts. In the upper rows the "
        r"alarm count is set by the rule of Section~\ref{subsec:metrics-behaviour}, the baseline attacker's median "
        r"count under that window; in the lower rows the window is 60\,s and the count is set by hand. The first row "
        r"is the declared detector.}",
        r"  \label{tab:detector-sweep}",
        r"  \tablestyle\setlength{\tabcolsep}{5pt}",
        r"  \begin{tabular}{@{}rrr" + "r" * len(SERIES) + "@{}}",
        r"    \toprule",
        r"    Window (s) & Alarm count & Baseline flagged (\%) & " + " & ".join(LABEL[p] for p in SERIES) + r" \\",
        r"    \midrule",
    ]
    for i, (w, th, rule, flagged, conf) in enumerate(rows):
        if i == len(WINDOWS):
            L.append(r"    \midrule")
        L.append("    %d & %d & %s & %s \\\\" % (w, th, pct(flagged), " & ".join(pct(conf[p]) for p in SERIES)))
    L += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    path = TAB_DIR / f"{STEM}.tex"
    path.write_text("\n".join(L))
    print(f"wrote {path.relative_to(REPO)}")
    for w, th, rule, flagged, conf in rows:
        print(f"  window {w:5.0f} s  count {th:.0f} ({'rule' if rule else 'set'})  baseline flagged {flagged:.3f}  "
              + "  ".join(f"{LABEL[p]} {conf[p]:.3f}" for p in SERIES)
              + f"  every APT profile above the baseline: {order_holds(conf)}")


if __name__ == "__main__":
    main()
