#!/usr/bin/env python3
"""Appendix table: time lost per MTD deployment under other splits of the
window around a deployment (Marc 2026-09-25 on the §4.5 draft: "every time you
see a number ... is this defensible, is this strictly conventional?").

REBASED 2026-09-29 (ruling A, handoff 2026-09-29_s45_equation_clarity.md): the
declared window is half the deployment interval each side, 1 000 s before and
1 000 s after at 2 000 s, so it has no free number; the split is what this table
moves, the before and after always summing to the interval so no window overlaps
the next deployment's. Time lost is now read in one slice (the window after
times the share of pace lost), so the bin width is no part of it and is no
longer swept. Every value is recomputed from the corpus through disruption.py's
own estimator; nothing is hard-coded.

Usage: python tools/ch5_timelost_window_table.py
"""
from __future__ import annotations

import sys

import numpy as np

from _ch5_style import LONG, TAB_DIR, REPO

sys.path.insert(0, str(REPO / "data" / "results" / "ch5_defended"))
import disruption as D  # noqa: E402

INTERVAL = 2000
BEFORES = (500, 750, 1000, 1250, 1500)
DECLARED = 1000
WIDTH = 125.0            # the curve's bins; time lost reads one slice, so the width changes nothing
ARMS = (("movement", "APT attacker model"), ("baseline", "Baseline attacker"))
STEM = "tab_C-5_timelost_window"


def time_lost(before: int) -> dict:
    after = INTERVAL - before
    D.EDGES = np.concatenate([np.arange(-before, 0, WIDTH), np.arange(0, after + WIDTH / 2, WIDTH)])
    D.PRE = D.EDGES[:-1] < 0
    runs = D.load({INTERVAL})
    none = {(r["arm"], r["profile"], r["seed"]): r for r in runs if r["cond"] == "none"}
    out = {}
    for arm, _ in ARMS:
        for m in D.MECHANISMS:
            rs = [r for r in runs if r["arm"] == arm and r["cond"] == m and r["interval"] == INTERVAL]
            num, den = D._stack(rs, None)
            pn, pd = D._stack(rs, none)
            out[(arm, m)] = D._time_lost(num.sum(0), den.sum(0)) - D._time_lost(pn.sum(0), pd.sum(0))
    return out


def main() -> None:
    grid = {b: time_lost(b) for b in BEFORES}
    lines = [
        "% GENERATED by tools/ch5_timelost_window_table.py --- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \caption[Time lost per MTD deployment under other splits of its window]{Time lost per MTD deployment, in "
        r"seconds, at the 2\,000\,s deployment interval, with the window around a deployment split into the seconds "
        r"before and after it in five ways; the two parts always sum to the interval, and 1\,000 before and "
        r"1\,000 after is the declared split.}",
        r"  \label{tab:timelost-window}",
        r"  \tablestyle\setlength{\tabcolsep}{4pt}",
        r"  \begin{tabular}{@{}l" + "r" * (2 * len(BEFORES)) + "@{}}",
        r"    \toprule",
        "    & " + " & ".join(r"\multicolumn{%d}{c}{%s}" % (len(BEFORES), name) for _, name in ARMS) + r" \\",
        "    " + " ".join(r"\cmidrule(lr){%d-%d}" % (2 + i * len(BEFORES), 1 + (i + 1) * len(BEFORES))
                         for i in range(len(ARMS))),
        "    Before (s) & " + " & ".join(_n(b) for _ in ARMS for b in BEFORES) + r" \\",
        "    After (s) & " + " & ".join(_n(INTERVAL - b) for _ in ARMS for b in BEFORES) + r" \\",
        r"    \midrule",
    ]
    order = sorted(D.MECHANISMS, key=lambda m: -grid[DECLARED][("movement", m)])
    for m in order:
        cells = []
        for arm, _ in ARMS:
            for b in BEFORES:
                v = "%d" % round(grid[b][(arm, m)])
                cells.append(("$-$" + v[1:]) if v.startswith("-") else v)
        lines.append("    %s & %s \\\\" % (LONG[m], " & ".join(cells)))
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    path = TAB_DIR / f"{STEM}.tex"
    path.write_text("\n".join(lines))
    print(f"wrote {path.relative_to(REPO)}")
    for b in BEFORES:
        print(b, {f"{a}|{m}": round(grid[b][(a, m)]) for a, _ in ARMS for m in D.MECHANISMS})


def _n(v: int) -> str:
    return r"1\,%03d" % (v - 1000) if v >= 1000 else str(v)


if __name__ == "__main__":
    main()
