"""The dwell-time catalogue tables --- chapter parameter table + appendix derivation.

Two floats from one declared family, emitted from `data/ogasp/tactic_durations.json`
so no value is ever typed (`figure_table_conventions.md` §h):

* `tab:dwell-catalogue` (§4.4.2) --- one row per shared duration: its
  tactics, its source (MTDSim's time, or declared) and the mean duration
  (round 4, 2026-10-05: three columns; the work each tactic does is the
  prose's). Since 2026-10-05 (Marc:
  the per-tactic table "reads like 15 random numbers"; "how they came from
  MTDSim and the baseline attacker"), overturning the one-panel ruling of
  2026-09-08 on merit.
* `tab:dwell-derivation` (`app:dwell-derivation`) --- the **why**: per-tactic
  family (with its value), multiplier, band and reason. The anchor-families
  table (`tab:dwell-anchors`) was cut 2026-10-04: section 4.4.2 says it.

The what/why split is Marc's ruling (2026-08-20); the one-panel chapter table
his ruling of 2026-09-08.

Axis: `_tactic_axis.matrix_order` --- these tables draw no lifecycle bands, and
matrix order is what `fig:l1-graph` takes, so the §b6 cross-figure contract
holds. Display names and the ATT&CK version pin come from the pinned bundle
through that module, never from a local map.

Usage:  python tools/dwell_catalogue_tables.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _tactic_axis import load_axis  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from mtdnetwork.data import constants  # noqa: E402  MTDSim's attack-action costs
CATALOGUE = REPO / "data" / "ogasp" / "tactic_durations.json"
OUT_DIR = REPO / "docs" / "thesis" / "tables"

# Presentation names for the anchor families and for where each family's shape
# came from. Names only --- every *value* is read from the catalogue
# (conventions §g: presentation names are part of the spec and are mapped here,
# never raw identifiers in the float; §h: no value typed).
# Round 3, 2026-10-05 (Marc: "family" and "shape" are "so vague"; the coined
# names are cut from the chapter): each set of tactics sharing a duration is
# described by the work its tactics do, and its value by what it was set from.
WORK = {
    ("exploit-shaped", 1.0): "A brief act on one host",
    ("scan-shaped", 1.0): "Survey hosts",
    ("stealth-low-and-slow", 1.0): "Kept up quietly over time",
    ("stealth-low-and-slow", 0.5): "Short acts among the quiet tactics",
    ("objective-execution", 1.0): "Move or destroy data",
    ("prep-off-network", 0.0): "Off the network, before the attack",
}
ROW_ORDER = list(WORK)
# The reference value each appendix row multiplies, named as the chapter names it.
REFERENCE = {
    "exploit-shaped": "Median exploit",
    "scan-shaped": "Three scans",
    "stealth-low-and-slow": "Declared",
    "objective-execution": "Declared",
    "prep-off-network": "---",
}


def esc(s: str) -> str:
    """LaTeX-escape a presentation string."""
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_")):
        s = s.replace(a, b)
    return s


def num(x: float) -> str:
    return f"{x:.1f}"


def main() -> None:
    cat = json.loads(CATALOGUE.read_text())
    anchors, tactics = cat["anchors"], cat["tactics"]
    axis = load_axis()

    # The axis is a contract: fail loudly if the catalogue's tactic set has
    # drifted from the pinned bundle rather than emitting a table against a
    # tactic set ATT&CK does not carry.
    axis.check_against(list(tactics))

    version, pin = cat["meta"]["version"], axis.version
    banner = (f"% GENERATED by tools/dwell_catalogue_tables.py from\n"
              f"%   data/ogasp/tactic_durations.json ({version}); tactic axis and\n"
              f"%   display names from the pinned ATT&CK bundle (v{pin}).\n"
              f"% Do not hand-edit; regenerate. Requires booktabs (already in the preamble).\n")

    # ---------------------------------------------------------- chapter ----
    # ONE ROW PER FAMILY VALUE since 2026-10-05 (Marc: the per-tactic table
    # "reads like 15 random numbers ... where do you get them from"; the
    # families "we don't really explain"). Each row: the family, its tactics,
    # what its value is set from, and the value. The two families MTDSim costs
    # are recomputed here from MTDSim's own constants and checked against the
    # catalogue, so the table cannot claim a source the value does not have.
    # Per-tactic multipliers, bands and reasons stay the appendix's.
    cost = constants.ATTACK_DURATION
    scan = ("SCAN_HOST", "SCAN_PORT", "SCAN_NEIGHBOR")
    scan_s = sum(cost[k] for k in scan)
    median_cx = (constants.VULN_MIN_COMPLEXITY + 1) / 2
    exploit_s = cost["EXPLOIT_VULN"] * (1 - median_cx)
    assert abs(scan_s - anchors["scan-shaped"]["duration_s"]) < 1e-9, scan_s
    assert abs(exploit_s - anchors["exploit-shaped"]["duration_s"]) < 1e-9, exploit_s

    # Round 4, 2026-10-05 (Marc: "what they do" and "set from" vague): the
    # source cell names the MTDSim time as Section 2.2.3 gives it, or says the
    # value is declared; the work each tactic does is the prose's.
    def source(anchor: str, mult: float) -> str:
        if anchor == "scan-shaped":
            return ("MTDSim, the three scans' total "
                    f"(${' + '.join(str(cost[k]) for k in scan)}$\\,s)")
        if anchor == "exploit-shaped":
            return "MTDSim, an exploit's median time"
        return "Declared"

    rows: dict[tuple[str, float], list[str]] = {}
    for name in axis.matrix_order:
        e = tactics[name]
        rows.setdefault((e["anchor"], e["relative_multiplier"]), []).append(name)
    assert set(rows) == set(WORK), set(rows) ^ set(WORK)
    keys = sorted(rows, key=ROW_ORDER.index)

    short = "The tactic durations"
    caption = (
        "The mean duration of each tactic, and its source. "
        "Appendix~\\ref{app:dwell-derivation} gives each tactic's reason."
    )
    L = [banner, r"\begin{table}[htbp]", r"\centering",
         rf"\caption[{short}]{{{caption}}}", r"\label{tab:dwell-catalogue}",
         r"\tablestyle",
         r"\begin{tabular}{@{}P{0.42\textwidth} P{0.32\textwidth} >{\raggedleft\arraybackslash}p{0.16\textwidth}@{}}", r"\toprule",
         r"Tactics & Source & Mean tactic duration $\mu_p$ (s) \\", r"\midrule"]
    for anchor, mult in keys:
        names = [axis.label[n] for n in rows[(anchor, mult)]]
        names = [names[0]] + [n[0].lower() + n[1:] for n in names[1:]]
        mu = {tactics[n]["duration_s"] for n in rows[(anchor, mult)]}
        assert len(mu) == 1, mu
        L.append(f"{esc(', '.join(names))} & "
                 f"{source(anchor, mult)} & {num(mu.pop())} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (OUT_DIR / "tab_4-4a_dwell_catalogue.tex").write_text("\n".join(L))

    # --------------------------------------------------------- appendix ----
    # ONE TABLE since 2026-10-04 (appendix pass, Marc: "is it relevant ... are
    # we answering that question"). The anchor-families table (tab:dwell-anchors)
    # is cut: section 4.4.2 already names the four families, their values and
    # which two the simulator costs, so the table repeated the chapter. Its one
    # remaining fact, each family's value, is now the Family cell here, and the
    # repo-path footnote is cut (voice.md §e). Reasons are the catalogue's
    # short_justification, rewritten in the chapter's terms the same day.
    short_a = "How each tactic duration was set"
    caption_a = (
        "How each tactic duration of Table~\\ref{tab:dwell-catalogue} was set "
        "(Section~\\ref{subsec:dwell-times}): a reference value, in brackets, "
        "times the tactic's multiplier. \\emph{Band} is the declared range of the "
        "multiplier."
    )
    A = [banner, r"\begin{table}[htbp]", r"\centering",
         rf"\caption[{short_a}]{{{caption_a}}}", r"\label{tab:dwell-derivation}",
         r"\tablestyle",
         r"\begin{tabular}{@{}P{0.15\textwidth} P{0.13\textwidth} r r c P{0.29\textwidth}@{}}", r"\toprule",
         r"Tactic & Reference (s) & Multiplier & Duration (s) & Band & Reason \\",
         r"\midrule"]
    for name in axis.matrix_order:
        e = tactics[name]
        lo, hi = e["sweep_range"]
        band = "---" if lo == hi == 0 else f"[{lo:g}, {hi:g}]"
        mult = "---" if e["anchor"] == "prep-off-network" else f"{e['relative_multiplier']:.1f}"
        fam = ("---" if e["anchor"] == "prep-off-network" else
               f"{REFERENCE[e['anchor']]} ({num(anchors[e['anchor']]['duration_s'])})")
        A.append(f"{esc(axis.label[name])} & {fam} & {mult} & "
                 f"{num(e['duration_s'])} & {band} & {esc(e['short_justification'])} \\\\")
    A += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (OUT_DIR / "tab_B-4a_dwell_derivation.tex").write_text("\n".join(A))

    print(f"wrote {OUT_DIR/'tab_4-4a_dwell_catalogue.tex'}")
    print(f"wrote {OUT_DIR/'tab_B-4a_dwell_derivation.tex'}")
    print(f"  {len(tactics)} tactics, {len(anchors)} families, "
          f"{len(set(t['duration_s'] for t in tactics.values()))} distinct values; "
          f"catalogue {version}, ATT&CK v{pin}")


if __name__ == "__main__":
    main()
