#!/usr/bin/env python3
"""Appendix B: the total tactic-to-action mapping against the partial one.

Section 4.4.3 says a total mapping, one attack action for every tactic, ran
the baseline attacker's ordered procedure in a stochastic order; this table
is what happened. It replaces the typed Experiment 1 table (2026-10-04
appendix pass): that table held the pre-redraft profile names and a 10-seed
run under the superseded regime, and did not hold the number Table C.1 quotes
for it.

Every number is read from data/results/ch5_s51_sensitivity/numbers.json, the
"mapping" block the section 5.1 re-run recorded at the chapter's pins (the
attacker model pooled over its four attack profiles, 400 runs per cell); the
record is docs/implementation/pipeline/ogasp/ch5_s51_sensitivity_findings.md
section 5. Nothing is typed here.

"Refused", not "blocked": blocked is the attack action an MTD deployment
disrupts (section 4.5); refused is the attack action the simulator turns down
because its precondition is not met (n_blocked / n_actions in the run record).

Usage:  python tools/total_mapping_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
NUMBERS = REPO / "data" / "results" / "ch5_s51_sensitivity" / "numbers.json"
OUT = REPO / "docs" / "thesis" / "tables" / "tab_B-7a_total_mapping.tex"

# The run record's condition keys, in the order chapter 5 reads them, and the
# names the thesis gives them.
CONDITION = {
    "none@0": "No MTD",
    "random@200": r"Random deployment strategy, 200\,s interval",
    "random@2000": r"Random deployment strategy, 2\,000\,s interval",
}
MAPPING = {"partial": r"Partial (Figure~\ref{fig:controller-mapping})", "forced_total": "Total"}


def main() -> None:
    m = json.loads(NUMBERS.read_text())["mapping"]
    if set(m) != set(CONDITION):
        raise SystemExit(f"conditions in the record {sorted(m)} are not {sorted(CONDITION)}")
    n = {c["hosts"]["n"] for cond in m.values() for c in cond.values()}
    if len(n) != 1:
        raise SystemExit(f"cells differ in run count: {sorted(n)}")
    runs = n.pop()

    L = [
        "% GENERATED by tools/total_mapping_table.py from",
        "%   data/results/ch5_s51_sensitivity/numbers.json (the mapping block). Do not",
        "%   hand-edit; regenerate. DRAFT STATE (2026-10-04 appendix pass): caption",
        "%   session-drafted, ratify on read.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption[The total tactic-to-action mapping against the partial one]{The APT "
        r"attacker model under the partial tactic-to-action mapping and under a total one, "
        + "with its four attack profiles pooled (" + f"{runs:,}".replace(",", r"\,") + " runs per row)."
        + r" \emph{Refused} is the share of attack actions the simulator turned down because "
        r"their precondition was not met. Intervals are 95\,\%.}",
        r"\label{tab:experiment-one}",
        r"\tablestyle",
        r"\begin{tabular}{@{}l r r r@{}}",
        r"\toprule",
        r"Mapping & Distinct hosts reached & Attack actions & Refused (\%) \\",
        r"\midrule",
    ]
    for k, (key, name) in enumerate(CONDITION.items()):
        if k:
            L.append(r"\midrule")
        L.append(rf"\grouprow{{4}}{{{name}}} \\")
        for mk, mname in MAPPING.items():
            c = m[key][mk]
            L.append(rf"{mname} & ${c['hosts']['mean']:.2f} \pm {c['hosts']['ci95']:.2f}$ & "
                     rf"{c['actions']['mean']:.0f} & {100 * c['blocked_fraction']:.0f} \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(REPO)}")
    for key in CONDITION:
        print("  " + key + ": " + "; ".join(
            f"{mk} {m[key][mk]['hosts']['mean']:.2f} hosts, refused {m[key][mk]['blocked_fraction']:.2f}"
            for mk in MAPPING))


if __name__ == "__main__":
    main()
