"""`tab:value-bases` (Appendix C) --- every value of the APT attacker model and its basis.

The table behind the two sentences that close the section 4.4 preamble (Marc
2026-10-04: the four-bases list was where clarity dropped, so the body keeps two
sentences and the list becomes this table). One row per value: what it is, its
basis (one of four: the corpus, MTDSim's own costs, the literature, our
judgement), where the dissertation gives its reason, and the test that varies or
removes it.

Every word comes from `data/ogasp/value_bases.json`; nothing is typed here. The
script checks that every row's basis is one of the four, and prints the count of
judgement values Chapter 5 and Appendix C leave untested, which the body's
second sentence states (three).

Usage:  python tools/value_bases_table.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LABELS = REPO / "data" / "ogasp" / "value_bases.json"
OUT = REPO / "docs" / "thesis" / "tables" / "tab_C-0b_value_bases.tex"


def main() -> int:
    d = json.loads(LABELS.read_text())
    bases = d["bases"]
    rows = d["rows"]
    bad = [r["value"] for r in rows if r["basis"] not in bases]
    if bad:
        raise SystemExit(f"basis not one of {bases}: {bad}")
    rows = sorted(rows, key=lambda r: bases.index(r["basis"]))     # stable: JSON order within a basis
    untested = [r["value"] for r in rows if r["basis"] == "Our judgement" and r["test"] == "not tested"]

    body, last = [], None
    for r in rows:
        basis = r["basis"] if r["basis"] != last else ""
        if last is not None and r["basis"] != last:
            body.append("    \\addlinespace")
        last = r["basis"]
        body.append(f"    {basis} & {r['value']} & {r['reason']} & {r['test']} \\\\")
    tex = f"""% GENERATED by tools/value_bases_table.py from data/ogasp/value_bases.json --- do not hand-edit.
% DRAFT STATE (2026-10-04, 4.4 preamble redraft): caption session-drafted, ratify on read.
\\begin{{table}}[htbp]
  \\centering
  \\caption[Each value of the APT attacker model and its basis]{{Each value of
  the APT attacker model, grouped by its basis, with where its reason is given
  and the test that varies, substitutes or removes it. A blank test cell: the
  value is not varied.}}
  \\label{{tab:value-bases}}
  \\tablestyle
  \\begin{{tabular}}{{@{{}}P{{2.2cm}}P{{5.2cm}}P{{2.6cm}}P{{4.4cm}}@{{}}}}
    \\toprule
    Basis & Value & Reason & Tested \\\\
    \\midrule
{chr(10).join(body)}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    OUT.write_text(tex)
    print(f"wrote {OUT.relative_to(REPO)}: {len(rows)} values; untested judgement values: {len(untested)} ({'; '.join(untested)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
